### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by valavanisleonidas** [iden3/react-native-circom-witnesscalc#1]
Hey thanks for the library. it is very useful. I am trying to run it for witness calculation using wasm.

When I first tried to run using android RN version 0.75.4 i got this error 

```
/android/app/src/debug/AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [io.iden3:circomwitnesscalc:0.0.1-alpha.1] AndroidManifest.xml:8:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-10:50 to override.
```
I added 

```
 android:allowBackup="false"
 android:theme="@style/AppTheme"
 tools:replace="android:allowBackup, android:theme"
```
and it seems to passed this error. when running the code though I just get `Error` without other information

my code is the following 

```
 const wasmBase64 = await RNFS.readFile(wasmPath, 'base64');
 const result = await calculateWitness(input, wasmBase64);
```
the input is a dictionary with values that I convert to a string. 

any ideas about the issue ? Does it run with wasm ? Because in the example I saw a graph

**Comment by 5eeman** [comment]
Hey,
Yeah, we are actually using not .wasm but .wcd (witness calc data, but I'm not sure) files. They're generated outta circuit files.
Please check original [circom-witnesscalc](https://github.com/iden3/circom-witnesscalc) library to get more details.

**Comment by 5eeman** [comment]
You added these to your app or to the example?
```
 android:allowBackup="false"
 android:theme="@style/AppTheme"
 tools:replace="android:allowBackup, android:theme"
```

**Comment by valavanisleonidas** [comment]
> You added these to your app or to the example?
> 
> ```
>  android:allowBackup="false"
>  android:theme="@style/AppTheme"
>  tools:replace="android:allowBackup, android:theme"
> ```

I added these in my app. I haven't used your example :) I can share my settings if needed. I think the RN version is the same as the example

**Comment by 5eeman** [comment]
Honestly unfortunately I have no idea what is this caused by.
Thanks for feedback.

**Comment by valavanisleonidas** [comment]
@5eeman I tried to convert my circom with this [circom-witnesscalc](https://github.com/iden3/circom-witnesscalc) but I have problems completing it. Do you have any idea about this library ? We have opened an issue about it but no answer yet. (https://github.com/iden3/circom-witnesscalc/issues/11)

thanks
